#To retrieve a list of all books:
#GET http://localhost:4000/api/v1/books

#GET a Specific Book by ID

GET http://localhost:4000/api/v1/books/1 

#POST a New Book


POST http://localhost:4000/api/v1/books
#Links to an external site.

Content-Type: application/json

{
    "title": "Harry Potter and the Sorcerer's Stone",
    "author": "J.K. Rowling",
    "genre": "Fantasy",
    "year": 1997
}